def printControls():
    print("Controls:") 
    print("p: pause/unpause")
    print("-: slow down")
    print("=: speed up")
    print("x: exit")
    print("h: show controls")
    print("middle mouse click: describe tile")
    print("left mouse click: paint tile (Can he held down)")
    print("right mouse click: eye drop tile")
    print("m: spawnCritter")
    print("o: iterate forward through terrain types")
    print("i: iterate backwards through terrain types")
    print()
